version: '3.1'
services:
  db:
    image: postgres:14.6-alpine
    container_name: db_for_asyncio
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5429:5432"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.alembic
    container_name: migrate_alembic
    environment:
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_HOST: ${POSTGRES_HOST}
      PG_PORT: ${POSTGRES_PORT}
      PG_DB: ${POSTGRES_DB}

    depends_on:
      - db
