version: '3.1'
services:
  db:
    image: postgres:14.6-alpine
    container_name: db_for_asyncio
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5429:5432"
