"""Initial

Revision ID: 95b79051aea6
Revises: 
Create Date: 2022-12-21 14:29:07.972957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b79051aea6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('people_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'people', ['people_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'people_id')
    # ### end Alembic commands ###
