"""new migration

Revision ID: fea01ac53974
Revises: 
Create Date: 2022-12-23 14:05:29.377505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea01ac53974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('birth_year', sa.String(length=15), nullable=True),
    sa.Column('eye_color', sa.String(length=15), nullable=True),
    sa.Column('films', sa.String(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('hair_color', sa.String(length=15), nullable=True),
    sa.Column('height', sa.String(length=10), nullable=True),
    sa.Column('homeworld', sa.String(length=100), nullable=True),
    sa.Column('mass', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('skin_color', sa.String(length=25), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('vehicles', sa.String(), nullable=True),
    sa.Column('starships', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('people_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
